// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBduoasfhUnyWygJkQWN-RL2WkdM1kT63k',
    appId: '1:421304804353:web:20f8218ce8e8afe982cc00',
    messagingSenderId: '421304804353',
    projectId: 'trainbookingsystem-6dec5',
    authDomain: 'trainbookingsystem-6dec5.firebaseapp.com',
    storageBucket: 'trainbookingsystem-6dec5.firebasestorage.app',
    measurementId: 'G-868XBV7P3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aHIEN8R1lVUVAQygehAmtoJINsuHiQ4',
    appId: '1:421304804353:android:4f4125dec94f64cb82cc00',
    messagingSenderId: '421304804353',
    projectId: 'trainbookingsystem-6dec5',
    storageBucket: 'trainbookingsystem-6dec5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBLTUFbVMmm1v9i3QEEqaqq9uakLlkX0',
    appId: '1:421304804353:ios:6d9c45e4a0f06e9982cc00',
    messagingSenderId: '421304804353',
    projectId: 'trainbookingsystem-6dec5',
    storageBucket: 'trainbookingsystem-6dec5.firebasestorage.app',
    iosBundleId: 'com.example.trainBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPBLTUFbVMmm1v9i3QEEqaqq9uakLlkX0',
    appId: '1:421304804353:ios:6d9c45e4a0f06e9982cc00',
    messagingSenderId: '421304804353',
    projectId: 'trainbookingsystem-6dec5',
    storageBucket: 'trainbookingsystem-6dec5.firebasestorage.app',
    iosBundleId: 'com.example.trainBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBduoasfhUnyWygJkQWN-RL2WkdM1kT63k',
    appId: '1:421304804353:web:d3fe29915754438682cc00',
    messagingSenderId: '421304804353',
    projectId: 'trainbookingsystem-6dec5',
    authDomain: 'trainbookingsystem-6dec5.firebaseapp.com',
    storageBucket: 'trainbookingsystem-6dec5.firebasestorage.app',
    measurementId: 'G-QGC8HSJL8H',
  );
}
